services:
  pi3:
    image: ghcr.io/bkmz2000/pi3:latest
    container_name: pi3
    restart: unless-stopped
    ports:
      - "8080:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - DB_PATH=/app/db/pi3.db
      - SESSION_SECRET=${SESSION_SECRET}
      - LOGINUS_DOMAIN=${LOGINUS_DOMAIN:-https://lk.systematika.org}
      - LOGINUS_CLIENT_ID=${LOGINUS_CLIENT_ID}
      - LOGINUS_CLIENT_SECRET=${LOGINUS_CLIENT_SECRET}
      - APP_BASE_URL=${APP_BASE_URL:-https://pi3.sys5.ru}
      - LOGINUS_TEACHER_ROLE=${LOGINUS_TEACHER_ROLE:-teacher}
    env_file:
      - .env
    volumes:
      - pi3-db:/app/db

volumes:
  pi3-db:
    driver: local